name: Publish Python distributions to PyPI and TestPyPI

on:
  workflow_dispatch:

jobs:
    python-build-n-publish:
        name: Build and publish Python distribution
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-python@v3

            - name: Initialize Python 3.9
              uses: actions/setup-python@v1
              with:
                python-version: 3.9

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install build

            - name: Build binary wheel and a source tarball
              run: python ./setup.py sdist

            - name: Publish distribution to Test PyPI
              uses: pypa/gh-action-pypi-publish@master
              with:
                user: crishna0401
                password: ${{ secrets.TESTPYPI }}